//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMapLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMapLocalizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteMapLocalizations", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشات تحليلي.
        /// </summary>
        internal static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتساب سنسور به دام.
        /// </summary>
        internal static string Assign_Sensor_To_Cattle {
            get {
                return ResourceManager.GetString("Assign_Sensor_To_Cattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقويم.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت دام.
        /// </summary>
        internal static string Cattle {
            get {
                return ResourceManager.GetString("Cattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت دام.
        /// </summary>
        internal static string Cattle_Activity {
            get {
                return ResourceManager.GetString("Cattle_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های مربوط به فعالیت دام در حال فراخوانی است. لطفا شکیبا باشید....
        /// </summary>
        internal static string Cattle_Activity_Loading {
            get {
                return ResourceManager.GetString("Cattle_Activity_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دمای بدن دام.
        /// </summary>
        internal static string Cattle_Body_Temp {
            get {
                return ResourceManager.GetString("Cattle_Body_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های مربوط به دمای بدن دام در حال فراخوانی است. لطفا شکیبا باشید....
        /// </summary>
        internal static string Cattle_Body_Temp_Loading {
            get {
                return ResourceManager.GetString("Cattle_Body_Temp_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت گروه.
        /// </summary>
        internal static string Cattle_Group {
            get {
                return ResourceManager.GetString("Cattle_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليست گروه ها.
        /// </summary>
        internal static string Cattle_Group_list {
            get {
                return ResourceManager.GetString("Cattle_Group_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت گله.
        /// </summary>
        internal static string Cattle_Herd {
            get {
                return ResourceManager.GetString("Cattle_Herd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليست گله ها.
        /// </summary>
        internal static string Cattle_Herd_List {
            get {
                return ResourceManager.GetString("Cattle_Herd_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت دام.
        /// </summary>
        internal static string Cattle_Insert {
            get {
                return ResourceManager.GetString("Cattle_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليست دام ها.
        /// </summary>
        internal static string Cattle_List {
            get {
                return ResourceManager.GetString("Cattle_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت دام.
        /// </summary>
        internal static string Cattle_Position {
            get {
                return ResourceManager.GetString("Cattle_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های مربوط به موقعیت دام در حال فراخوانی است. لطفا شکیبا باشید....
        /// </summary>
        internal static string Cattle_Position_Loading {
            get {
                return ResourceManager.GetString("Cattle_Position_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايجاد پيام.
        /// </summary>
        internal static string ComposeMessage {
            get {
                return ResourceManager.GetString("ComposeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR.
        /// </summary>
        internal static string culture {
            get {
                return ResourceManager.GetString("culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش گروهی دام ها.
        /// </summary>
        internal static string Edit_GroupOf_Cattle {
            get {
                return ResourceManager.GetString("Edit_GroupOf_Cattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديريت بهاربند.
        /// </summary>
        internal static string Free_Stall {
            get {
                return ResourceManager.GetString("Free_Stall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليست بهاربندها.
        /// </summary>
        internal static string Free_Stall_List {
            get {
                return ResourceManager.GetString("Free_Stall_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های محیطی.
        /// </summary>
        internal static string Free_Stall_Plot {
            get {
                return ResourceManager.GetString("Free_Stall_Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق ورودي.
        /// </summary>
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت دام.
        /// </summary>
        internal static string Insert_Cattle {
            get {
                return ResourceManager.GetString("Insert_Cattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت گروه.
        /// </summary>
        internal static string Insert_Cattle_Group {
            get {
                return ResourceManager.GetString("Insert_Cattle_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت گله.
        /// </summary>
        internal static string Insert_Cattle_Herd {
            get {
                return ResourceManager.GetString("Insert_Cattle_Herd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت بهاربند.
        /// </summary>
        internal static string Insert_Free_Stall {
            get {
                return ResourceManager.GetString("Insert_Free_Stall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليست حسگرها.
        /// </summary>
        internal static string Insert_Sensor {
            get {
                return ResourceManager.GetString("Insert_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راهنما.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پيام.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغذيه دام.
        /// </summary>
        internal static string Nutrition {
            get {
                return ResourceManager.GetString("Nutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان يابي.
        /// </summary>
        internal static string Positioning {
            get {
                return ResourceManager.GetString("Positioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی لیست سنسورها.
        /// </summary>
        internal static string Reload_Sensors {
            get {
                return ResourceManager.GetString("Reload_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش تجهیزات.
        /// </summary>
        internal static string Report_Equipment {
            get {
                return ResourceManager.GetString("Report_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسگر.
        /// </summary>
        internal static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت حسگر.
        /// </summary>
        internal static string Sensor_List {
            get {
                return ResourceManager.GetString("Sensor_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظيمات.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
    }
}
