// <auto-generated />
namespace SmartCattle.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mergefarmandfarmmap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mergefarmandfarmmap));
        
        string IMigrationMetadata.Id
        {
            get { return "201708120454018_merge farm and farmmap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
